name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        os: ['self-hosted']
        ruby-version: ['3.3', '3.2', '3.1', '3.0', '2.7']

    name: Ruby ${{ matrix.ruby-version }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    # Option 1: Remove existing ruby-build directory (if present)
    # Uncomment this option if you're confident there are no issues with potentially existing ruby-build data.
    #- name: Remove existing ruby-build directory (if present)
    #  run: rm -rf ~/.rbenv/plugins/ruby-build

    # Option 2: Install rbenv and ruby-build (if not already installed)
    - name: Install rbenv and ruby-build (if not already installed)
      run: |
        if [ ! -d ~/.rbenv/plugins/ruby-build ]; then
          curl -fsSL https://raw.githubusercontent.com/rbenv/rbenv-installer/master/install.sh | bash
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
          echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc
        fi

    - name: Install Ruby using rbenv
      run: |
        rbenv install ${{ matrix.ruby-version }}
        rbenv global ${{ matrix.ruby-version }}

    - name: Mark Ruby installation complete
      run: touch /opt/runner/_work/_tool/Ruby/${{ matrix.ruby-version }}/s390x.complete

    - name: Install dependencies
      run: bundle install

    - name: Run tests
      run: bundle exec rake test TESTOPTS="-v --no-show-detail-immediately"
