name: Test

on:
  push:
    branches: [s390x-ci]
  pull_request:
    branches: [s390x-ci]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        os: ['self-hosted']
        ruby-version: ['3.3', '3.2', '3.1', '3.0', '2.7']

    name: Ruby ${{ matrix.ruby-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        run: sudo apt-get update 
             && sudo apt-get install -y gcc make wget tar bison flex openssl libssl-dev libdb-dev libgdbm-dev libreadline-dev libyaml-dev 
             && wget http://cache.ruby-lang.org/pub/ruby/${{matrix.ruby-version}}/ruby-${{matrix.ruby-version}}.0.tar.gz 
             && tar zxf ruby-${{matrix.ruby-version}}.0.tar.gz 
             && cd ruby-${{matrix.ruby-version}}.0 
             && ./configure 
             && make 
             && sudo make install
      - name: Install addons
        if: ${{ matrix.os == 'self-hosted' }}
        run: sudo apt-get install -y libgmp3-dev libcap-ng-dev 
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake test TESTOPTS="-v --no-show-detail-immediately"
